GET http://localhost:5000/users


###

GET http://localhost:5000/users/66a1b3c699f06077b283f680


###

POST http://localhost:5000/users
Content-Type: application/json

{
    "username": "test123",
    "password_hash": "hashed_password",
    "email": "test123@example.com",
    "first_name": "test",
    "last_name": "123",
    "phone_number": "123-456-7890"
}

###

DELETE http://localhost:5000/users/66a1b3c699f06077b283f680

###

PATCH http://localhost:5000/users/66a1b84357a5b4447fb4187c
Content-Type: application/json

{
    "email": "newemailtest@gmail.com"
}